### ISSUE TITLE
use Schema; not found in 2021

### ISSUE THREAD

**Issue by jamesbriggs** [graphql-perl/GraphQL-Plugin-Convert-DBIC#22]
Hi.

The sample code has a 'use Schema;', but that's not found in CPAN in 2021, so I think that should be  'use DBIx::Class::Schema; '.

Am I correct?

/opt/perl-5.14.4/bin/perl -e 'use CPAN; install Schema'
Going to read '/root/.cpan/Metadata'
  Database was generated on Thu, 26 Aug 2021 02:55:55 GMT
Warning: Cannot install Schema, don't know what it is.
Try the command

    i /Schema/

**Comment by mohawk2** [comment]
It's intended to refer to your local `Schema` class! If I changed it to `use My::Local::Schema`, do you think that would be clearer?

**Comment by jamesbriggs** [comment]
Hi.

Maybe like that, or perhaps just put a comment above it saying something like:

"# refer to your application-specific version of Schema.pm. You may need 'use lib'"

(I feel strongly that the naked 'use Schema;' is very confusing, but I'm indifferent to the mechanism of how you clarify it.)

You might be able to pre-define the use lib 'path'; statement to work automatically.

Thanks, James.

**Comment by mohawk2** [comment]
Thanks for the report! Released as 0.18.
